server:
  port: 8181

## GCP configuration
spring:
  cloud:
    gcp:
      project-id: weighty-wonder-308406
      credentials:
        location: file:src/main/resources/service-account.json


## Application configuration
app:
 message:
   topic: 
      name: "transaction-topic"
   subscription:
      name: "transaction-subscription"
      name1: "transaction-notification-subscription"
             